New bugs found
tghp/unitary-fund pull request #45
Opened 2023-07-31 19:37 UTC by QuantumAli

**Done on this branch**
- Fixed certain issues on tags with the grants (removing additional duplicate tags)
- Removed ** from title

**Other Bugs Found**
- Also the slider for BlogSlider is not working, as of now it only looks at "Unitary Fund 2021 Annual Report"
- If it is possible to have tags under grants to be all lowercase. Some tags were written with uppercase, and this creates an additional tag on when filtering through

2023-07-31 20:14 UTC, WrathfulSpatula requested changes
Please fix the two typos, and then I'll approve.

2023-07-31 20:14 UTC, WrathfulSpatula commented on src/content/grant/2021_Quantum_algorithms.md
> +name: "Quantom Alogrithms"
"Quantum Algorithms"

2023-07-31 20:14 UTC, WrathfulSpatula commented on src/content/grant/2021_Quantum_algorithms.md
> +  - quantum alogrithm
"quantum algorithm"

2023-07-31 20:40 UTC, QuantumAli commented
Fixed them!

2023-07-31 20:58 UTC, WrathfulSpatula approved these changes

2023-08-01 11:53 UTC, nathanshammah approved these changes
Excellent fixes and finds @QuantumAli! Can you please open two additional issues on GH about the things you found out?

2023-08-01 11:53 UTC, merged